name: PR
on: [pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.15
        uses: actions/setup-go@v1
        with:
          go-version: 1.15
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Build
        run: CGO_ENABLED=0 go build -ldflags="-w -s" -o gogci

      - name: Setup Lint
        run: curl -LO https://github.com/golangci/golangci-lint/releases/download/v1.23.6/golangci-lint-1.23.6-linux-amd64.tar.gz && tar -xf golangci-lint-1.23.6-linux-amd64.tar.gz

      - name: Lint
        run: golangci-lint-1.23.6-linux-amd64/golangci-lint run

      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: gogci
          path: gogci
