name: Tag
on:
  push:
    tags:
      - 'v*.*.*'
      
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Build
      run: CGO_ENABLED=0 go build -ldflags="-w -s" -o gogci
      
    - name: Setup Lint
      run: curl -LO https://github.com/golangci/golangci-lint/releases/download/v1.23.6/golangci-lint-1.23.6-linux-amd64.tar.gz && tar -xf golangci-lint-1.23.6-linux-amd64.tar.gz
      
    - name: Lint
      run: golangci-lint-1.23.6-linux-amd64/golangci-lint run

    - name: Setup UPX
      run: curl -LO https://github.com/upx/upx/releases/download/v3.96/upx-3.96-amd64_linux.tar.xz && tar -xf upx-3.96-amd64_linux.tar.xz

    - name: Run UPX
      run: upx-3.96-amd64_linux/upx gogci
      
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: gogci
        asset_name: gogci
        tag: ${{ github.ref }}
        overwrite: true
