name: Tag
on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: Run Golang CI Lint
        uses: golangci/golangci-lint-action@v2

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Build
        run: CGO_ENABLED=0 go build -ldflags="-w -s" -o gogci

      - name: Setup UPX
        run: curl -LO https://github.com/upx/upx/releases/download/v3.96/upx-3.96-amd64_linux.tar.xz && tar -xf upx-3.96-amd64_linux.tar.xz

      - name: Run UPX
        run: upx-3.96-amd64_linux/upx gogci

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: gogci
          asset_name: gogci
          tag: ${{ github.ref }}
          overwrite: true
